// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Inputcourses struct {
	X int    `json:"x"`
	Y string `json:"y"`
}

type Inputstr struct {
	X int    `json:"x"`
	Y string `json:"y"`
	P string `json:"p"`
}

type Inputstr1 struct {
	Roll   int    `json:"roll"`
	Course string `json:"course"`
	Sem1   int    `json:"sem1"`
	Sem2   int    `json:"sem2"`
	Sem3   int    `json:"sem3"`
}

type Inputstr2 struct {
	Roll int    `json:"roll"`
	Name string `json:"name"`
}

type Inputvalues struct {
	X int `json:"x"`
	Y int `json:"y"`
}

type Inputvalues1 struct {
	X int `json:"x"`
	Y int `json:"y"`
}

type Marks struct {
	X  int    `json:"x"`
	Y  int    `json:"y"`
	Z  int    `json:"z"`
	Ro int    `json:"ro"`
	C  string `json:"c"`
}

type Outpurcourses struct {
	Z []*string `json:"z"`
}

type Outputstr struct {
	Z string `json:"z"`
}

type Outputstr1 struct {
	Total int `json:"total"`
}

type Outputstr2 struct {
	Result string `json:"result"`
}

type Outputvalues struct {
	Z string `json:"z"`
}

type Outputvalues1 struct {
	Z []*string `json:"z"`
}

type Testmarks struct {
	X int `json:"x"`
}

type Testtotal struct {
	T int `json:"t"`
}

type Total struct {
	T int `json:"t"`
}
